include:
  - local: 'ci/setup-dkml/gl/setup-dkml.gitlab-ci.yml'

stages:
  - prepare
  - build
  - test
  - deploy

variables:
  # We need the secondary switch ('two') to install dkml-build-desktop.opam
  SECONDARY_SWITCH: 'true'
  # Set to 'true' when you only want do the DKML setup but not the build-test
  # and not the release. Good for populating the cache.
  SETUP_ONLY: 'false'
  SKIP_RELEASE_WIN32: 'false'

linux:ci:release:build:
  extends: .linux:setup-dkml
  stage: build
  needs: [] # see comments in win32:build
  timeout: 2h
  script:
    - |
      if [ "$SETUP_ONLY" = "true" ]; then
        echo 'SKIPPING BUILD since SETUP_ONLY=true'
      else
        sh ci/build-test.sh ci release
      fi

linux:ci:next:build:
  extends: .linux:setup-dkml
  stage: build
  needs: [] # see comments in win32:build
  timeout: 2h
  script:
    - |
      if [ "$SETUP_ONLY" = "true" ]; then
        echo 'SKIPPING BUILD since SETUP_ONLY=true'
      else
        sh ci/build-test.sh ci next
      fi

# We use staging (two jobs) for Windows because without a cache
# the job will exceed 2 hours (the GitLab shared SaaS runner limit).
# Using SECONDARY_SWITCH=true is very expensive.
win32:prepare:
  extends: .win32:setup-dkml
  artifacts: {} # don't need artifacts for the prepare stage
  stage: prepare
  timeout: 2h
  script:
    - Write-Host "OCaml compiler caching complete."

win32:ci:release:build:
  extends: .win32:setup-dkml
  rules:
    - if: $SKIP_RELEASE_WIN32 != "true"
  stage: build
  # For reasons unknown (perhaps 'needs' has bugs with parallel matrix) the
  # following does not work. So instead we can
  # 1. Place `needs: []` to move other jobs ahead rather than delay this job.
  # 2. Place other jobs in prior stages.
  # We do #1 since #2 can cause a bigger block wait for this job (because
  # more jobs are in prior stages for #2).
  # needs:
  #   - job: win32:prepare
  timeout: 2h
  script:
    - |
      if ("$env:SETUP_ONLY" -eq "true") {
        Write-Host "SKIPPING BUILD since SETUP_ONLY=true"
      } else {
        msys64\usr\bin\bash -lc "ci/build-test.sh ci release"
      }

win32:ci:next:build:
  extends: .win32:setup-dkml
  stage: build
  timeout: 2h
  script:
    - |
      if ("$env:SETUP_ONLY" -eq "true") {
        Write-Host "SKIPPING BUILD since SETUP_ONLY=true"
      } else {
        msys64\usr\bin\bash -lc "ci/build-test.sh ci next"
      }

# macos:ci:release:build:
#   extends: .macos:setup-dkml
#   stage: build
#   needs: [] # see comments in win32:build
#   timeout: 2h
#   script:
#     - |
#       if [ "$SETUP_ONLY" = "true" ]; then
#         echo 'SKIPPING BUILD since SETUP_ONLY=true'
#       else
#         sh ci/build-test.sh ci release
#       fi

# macos:ci:next:build:
#   extends: .macos:setup-dkml
#   stage: build
#   needs: [] # see comments in win32:build
#   timeout: 2h
#   script:
#     - |
#       if [ "$SETUP_ONLY" = "true" ]; then
#         echo 'SKIPPING BUILD since SETUP_ONLY=true'
#       else
#         sh ci/build-test.sh ci next
#       fi

release:
  stage: deploy
  image: alpine
  rules:
    - if: $SETUP_ONLY != "true"
  script:
    - apk add jq rsync curl

    # Make _release
    - ci/prepare-release.sh

    # Create public packages
    - |
      if [ -z "$CI_COMMIT_TAG" ]; then
        PKGTAG="$CI_COMMIT_BRANCH"
      elif [ -n "$CI_COMMIT_TAG" ]; then
        PKGTAG=$(echo "$CI_COMMIT_TAG" | sed 's/^v//')
      else
        PKGTAG="$CI_COMMIT_SHORT_SHA"
      fi

    - CI_PROJECT_PATH_URLENCODED=$(printf %s "$CI_PROJECT_PATH" | jq -s -R -r @uri) # Must be url-encoded per https://docs.gitlab.com/ee/user/packages/generic_packages/
    - PACKAGE_REGISTRY_URL="${CI_API_V4_URL}/projects/$CI_PROJECT_PATH_URLENCODED/packages/generic/$THE_EXECUTABLE_NAME/$PKGTAG"
    - echo $PACKAGE_REGISTRY_URL
    - |
      GLAB_CURL_HEADER="JOB-TOKEN: ${CI_JOB_TOKEN}"
      find _release -mindepth 1 -maxdepth 1 -type f | while read -r releasefile; do
        curl --fail --header "$GLAB_CURL_HEADER" --upload-file "_release/$releasefile" "$PACKAGE_REGISTRY_URL/$releasefile"
      done

