(lang dune 2.9)

(name dkml-workflows)

(version 1.0.0)

(generate_opam_files true)

(source
 (github diskuv/dkml-workflows))

(license Apache-2.0)

(authors "Diskuv, Inc. <opensource+diskuv-ocaml@support.diskuv.com>")

(maintainers "opensource+diskuv-ocaml@support.diskuv.com")

(package
 (name dkml-workflows)
 (synopsis
  "GitLab CI/CD and GitHub Action workflows used by and with Diskuv OCaml (DKML) tooling")
 (description
  "GitLab CI/CD and GitHub Action workflows used by and with Diskuv OCaml (DKML) tooling.")
 (depends
  dune
  (astring
   (>= 0.8.5))
  (bos
   (>= 0.2.1))
  (crunch
   (>= 3.2.0))
  (jingoo
   (>= 1.4.4))
  (uutf
   (>= 1.0.3))))
